project: Flight Assessment of Risk Tool.xcodeproj
schemes:
  - FART
exclude_tests: true
exclude_targets:
  - FARTUnitTests
  - FARTUITests
report_exclude:
  - "**/Generate Screenshots/**"
retain_public: false
